package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ProgressBar;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;



public class MainController {
	@FXML
	private Button btnStart;

	// Event Listener on Button[#btnStart].onAction
	@FXML
	public void handleStartAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		if(event.getSource() == btnStart) {
			
			btnStart.getScene().getWindow().hide();
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("Choices.fxml"));
			primaryStage.close();
			
			Scene scene = new Scene(root);
			primaryStage.setScene(scene);
			primaryStage.setTitle("MetNow");
			primaryStage.show();
			
			
			
		}
	}
}
